# Generated by Django 5.2.15 on 2026-06-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrequest',
            name='project_type',
            field=models.CharField(choices=[('web_application', 'Web application'), ('client_portal', 'Client portal'), ('internal_tool', 'Internal tool'), ('odoo_system', 'Odoo system'), ('automation', 'Automation workflow'), ('api_integration', 'API integration'), ('mobile_application', 'Mobile application'), ('project_rescue', 'Project rescue'), ('other', 'Other')], max_length=32),
        ),
    ]
