# Generated by Django 5.2.15 on 2026-06-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projectrequest_project_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrequest',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectrequest',
            name='is_spam',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectrequest',
            name='spam_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='projectrequest',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
    ]
